#!/usr/bin/env python3
"""Workflow state synchronization, validation, initialization and preflight checks."""

from __future__ import annotations

import argparse
import json
import re
import secrets
import subprocess
import sys
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / "workflow" / "state.json"
GENERATED_JS_PATH = ROOT / "workflow" / "state.generated.js"
GOAL_PATH = ROOT / "docs" / "Goal任务计划-GoalPlan.md"
PROMPT_PATH = ROOT / "design" / "lovart" / "原型生图提示词-LovartPrompt.md"
APPS_ENV_PATH = ROOT / "apps" / ".env"
SCAFFOLD_REMOTE = "github.com/junkking233/fullstack-app-starter"
STATUS_LABELS = {
    "pending": "待开始",
    "in_progress": "进行中",
    "blocked": "阻塞",
    "completed": "已完成",
    "not_applicable": "不适用",
}
ALLOWED_STATUSES = set(STATUS_LABELS)
GOAL_START = "<!-- WORKFLOW:GENERATED:START -->"
GOAL_END = "<!-- WORKFLOW:GENERATED:END -->"


class WorkflowError(RuntimeError):
    pass


def load_state() -> dict:
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise WorkflowError(f"无法读取 {STATE_PATH.relative_to(ROOT)}: {exc}") from exc


def save_state(state: dict) -> None:
    STATE_PATH.write_text(
        json.dumps(state, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def parse_lovart_prompts() -> list[dict[str, str]]:
    if not PROMPT_PATH.exists():
        return []

    source = PROMPT_PATH.read_text(encoding="utf-8")
    heading_pattern = re.compile(r"^###\s+(P\d{2,})[-\s]+(.+?)\s*$", re.MULTILINE)
    headings = list(heading_pattern.finditer(source))
    prompts: list[dict[str, str]] = []
    for index, heading in enumerate(headings):
        section_end = headings[index + 1].start() if index + 1 < len(headings) else len(source)
        section = source[heading.end():section_end]
        code_match = re.search(r"```text\s*\n(.*?)\n```", section, re.DOTALL)
        if not code_match:
            continue
        prompts.append(
            {
                "id": heading.group(1),
                "title": heading.group(2).strip(),
                "prompt": code_match.group(1).strip(),
            }
        )
    return prompts


def render_goal_region(state: dict) -> str:
    project = state["project"]
    workflow = state["workflow"]
    current_stage = workflow["stages"][workflow["currentStage"]]
    blockers = workflow.get("blockers", [])
    blocker_text = "；".join(item["message"] for item in blockers) if blockers else "暂无"
    project_name = project["name"] or "尚未设置（模板模式）"
    lines = [
        GOAL_START,
        "",
        "> 本区域由 `workflow/state.json` 通过 `python3 scripts/workflow.py sync` 生成，请勿手工修改。",
        "",
        "| 项目 | 内容 |",
        "| --- | --- |",
        f"| 项目模式 | `{project['mode']}` |",
        f"| 业务名称 | {project_name} |",
        f"| 当前阶段 | {current_stage['id']}. {current_stage['name']} |",
        f"| 阶段状态 | {STATUS_LABELS[current_stage['status']]} |",
        f"| 当前任务 | {workflow['currentTask']} |",
        f"| 总进度 | {workflow['completedStages']} / {len(workflow['stages'])} 阶段 |",
        f"| 最近完成 | {workflow['recentlyCompleted']} |",
        f"| 下一步 | {workflow['nextStep']} |",
        f"| 阻塞项 | {blocker_text} |",
        f"| 最后更新 | {workflow['lastUpdated']} |",
        "",
        "### 阶段状态",
        "",
    ]
    for stage in workflow["stages"]:
        checked = "x" if stage["status"] in {"completed", "not_applicable"} else " "
        lines.append(
            f"- [{checked}] {stage['id']}. {stage['name']} — {STATUS_LABELS[stage['status']]}：{stage['summary']}"
        )

    lines.extend(["", "### 当前阶段门禁", ""])
    gates = workflow["gates"].get(str(workflow["currentStage"]), [])
    for gate in gates:
        checked = "x" if gate["status"] in {"completed", "not_applicable"} else " "
        evidence = f"；证据：{gate['evidence']}" if gate.get("evidence") else ""
        lines.append(
            f"- [{checked}] `{gate['id']}` {gate['label']}（{STATUS_LABELS[gate['status']]}{evidence}）"
        )
    lines.extend(["", GOAL_END])
    return "\n".join(lines)


def replace_generated_region(source: str, generated: str) -> str:
    if GOAL_START not in source or GOAL_END not in source:
        raise WorkflowError("GoalPlan 缺少工作流生成区域标记")
    start = source.index(GOAL_START)
    end = source.index(GOAL_END, start) + len(GOAL_END)
    return source[:start] + generated + source[end:]


def generated_js(state: dict, prompts: list[dict[str, str]]) -> str:
    payload = {"state": state, "lovartPrompts": prompts}
    return (
        "// Generated by scripts/workflow.py; do not edit manually.\n"
        "window.WORKFLOW_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )


def sync_files(state: dict) -> None:
    prompts = parse_lovart_prompts()
    GENERATED_JS_PATH.write_text(generated_js(state, prompts), encoding="utf-8")
    goal_source = GOAL_PATH.read_text(encoding="utf-8")
    GOAL_PATH.write_text(
        replace_generated_region(goal_source, render_goal_region(state)),
        encoding="utf-8",
    )


def git_remote() -> str:
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def validate_state(state: dict) -> list[str]:
    errors: list[str] = []
    project = state.get("project", {})
    workflow = state.get("workflow", {})
    stages = workflow.get("stages", [])

    if state.get("schemaVersion") != 1:
        errors.append("schemaVersion 必须为 1")
    if project.get("mode") not in {"template", "business"}:
        errors.append("project.mode 必须为 template 或 business")
    if workflow.get("gatePolicy") != "current_stage_only":
        errors.append("gatePolicy 必须为 current_stage_only")
    if [stage.get("id") for stage in stages] != list(range(6)):
        errors.append("stages 必须完整包含 0-5 且顺序一致")
        return errors

    for stage in stages:
        if stage.get("status") not in ALLOWED_STATUSES:
            errors.append(f"阶段 {stage.get('id')} 状态无效")
    for stage_id, gates in workflow.get("gates", {}).items():
        for gate in gates:
            if gate.get("status") not in ALLOWED_STATUSES:
                errors.append(f"阶段 {stage_id} 门禁 {gate.get('id')} 状态无效")
            if gate.get("status") in {"completed", "not_applicable"} and not gate.get("evidence", "").strip():
                errors.append(f"阶段 {stage_id} 门禁 {gate.get('id')} 完成但缺少证据")
    completed_count = sum(stage["status"] in {"completed", "not_applicable"} for stage in stages)
    if workflow.get("completedStages") != completed_count:
        errors.append("completedStages 与 stages 中的 completed 数量不一致")

    current_stage_id = workflow.get("currentStage")
    if not isinstance(current_stage_id, int) or not 0 <= current_stage_id < len(stages):
        errors.append("currentStage 必须是 0-5")
        return errors
    if workflow.get("currentStageStatus") != stages[current_stage_id]["status"]:
        errors.append("currentStageStatus 与当前阶段 status 不一致")

    seen_unfinished = False
    for stage in stages:
        if stage["status"] in {"completed", "not_applicable"}:
            if seen_unfinished:
                errors.append("已完成阶段必须连续，不能跨过未完成阶段")
            gates = workflow.get("gates", {}).get(str(stage["id"]), [])
            incomplete = [gate["id"] for gate in gates if gate.get("status") not in {"completed", "not_applicable"}]
            if incomplete:
                errors.append(f"阶段 {stage['id']} 已完成但门禁未闭合：{', '.join(incomplete)}")
        else:
            seen_unfinished = True

    if stages[current_stage_id]["status"] in {"completed", "not_applicable"} and current_stage_id < 5:
        errors.append("当前阶段完成后必须把 currentStage 推进到下一阶段")

    current_status = stages[current_stage_id]["status"]
    blockers = workflow.get("blockers", [])
    if current_status == "blocked" and not blockers:
        errors.append("当前阶段为 blocked 时必须记录 blocker")
    if blockers and current_status != "blocked":
        errors.append("存在 blocker 时当前阶段必须设为 blocked")
    for blocker in blockers:
        if not blocker.get("message") or not blocker.get("resumeAction"):
            errors.append("每个 blocker 必须包含 message 和 resumeAction")

    if project.get("mode") == "template":
        if completed_count != 0 or current_stage_id != 0:
            errors.append("模板模式不得继承业务阶段完成状态")
    else:
        db_name = project.get("databaseName", "")
        compose_name = project.get("composeProjectName", "")
        if not project.get("name"):
            errors.append("业务模式必须设置真实业务名称")
        if not re.fullmatch(r"[a-zA-Z][a-zA-Z0-9_]{2,63}", db_name):
            errors.append("databaseName 必须是 3-64 位 MySQL 标识符")
        if db_name == "template_db":
            errors.append("业务模式不得使用 template_db")
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{2,62}", compose_name):
            errors.append("composeProjectName 格式无效")
        if compose_name == "app-scaffold":
            errors.append("业务模式不得使用 app-scaffold Compose 项目名")
        if SCAFFOLD_REMOTE in git_remote():
            errors.append("业务模式的 origin 仍指向脚手架仓库")
        env_values = parse_env_file(APPS_ENV_PATH)
        if stages[0]["status"] == "completed":
            if env_values.get("APP_DB_NAME") != db_name:
                errors.append("apps/.env 的 APP_DB_NAME 与工作流状态不一致")
            if env_values.get("COMPOSE_PROJECT_NAME") != compose_name:
                errors.append("apps/.env 的 COMPOSE_PROJECT_NAME 与工作流状态不一致")
            secret = env_values.get("AUTH_TOKEN_SECRET", "")
            if len(secret) < 32 or secret.startswith("replace-"):
                errors.append("AUTH_TOKEN_SECRET 必须替换为至少 32 位随机值")
            if (ROOT / "templates").exists():
                errors.append("阶段 0 完成后必须删除 templates/")
            db_source = (ROOT / "db" / "db.sql").read_text(encoding="utf-8")
            if f"CREATE DATABASE IF NOT EXISTS {db_name}" not in db_source or f"USE {db_name};" not in db_source:
                errors.append("db/db.sql 尚未切换到业务独立数据库")

    stage_two = stages[2]
    if stage_two["status"] == "completed":
        prompts = parse_lovart_prompts()
        if not prompts:
            errors.append("阶段 2 已完成但没有可解析的 Lovart 单页提示词")
        prompt_ids = [prompt["id"] for prompt in prompts]
        if len(prompt_ids) != len(set(prompt_ids)):
            errors.append("Lovart 单页提示词页面编号重复")
        placeholder = re.compile(r"\{[^{}]+\}|Pxx|这里粘贴|【粘贴|待填写")
        for prompt in prompts:
            if placeholder.search(prompt["prompt"]):
                errors.append(f"{prompt['id']} 提示词仍包含占位符")
            output_files = [
                path for path in (ROOT / "design" / "lovart" / "pages").glob(f"{prompt['id']}-*")
                if path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".psd"}
            ]
            if not output_files:
                errors.append(f"{prompt['id']} 缺少 design/lovart/pages/ 单页原型图")

    if stages[3]["status"] == "completed":
        stitch_files = [path for path in (ROOT / "design" / "stitch").rglob("*") if path.is_file()]
        if not stitch_files:
            errors.append("阶段 3 已完成但 design/stitch/ 没有 screen/HTML/截图备份")

    return errors


def validate_generated_files(state: dict) -> list[str]:
    errors: list[str] = []
    expected_js = generated_js(state, parse_lovart_prompts())
    actual_js = GENERATED_JS_PATH.read_text(encoding="utf-8") if GENERATED_JS_PATH.exists() else ""
    if actual_js != expected_js:
        errors.append("workflow/state.generated.js 未同步，请运行 workflow.py sync")

    if GOAL_PATH.exists():
        source = GOAL_PATH.read_text(encoding="utf-8")
        try:
            expected_goal = replace_generated_region(source, render_goal_region(state))
        except WorkflowError as exc:
            errors.append(str(exc))
        else:
            if source != expected_goal:
                errors.append("GoalPlan 状态区未同步，请运行 workflow.py sync")
    else:
        errors.append("缺少 GoalPlan")
    return errors


def command_sync(_: argparse.Namespace) -> int:
    state = load_state()
    errors = validate_state(state)
    if errors:
        raise WorkflowError("状态校验失败：\n- " + "\n- ".join(errors))
    sync_files(state)
    print("已同步 GoalPlan 状态区和 workflow/state.generated.js")
    return 0


def command_validate(_: argparse.Namespace) -> int:
    state = load_state()
    errors = validate_state(state) + validate_generated_files(state)
    index_source = (ROOT / "index.html").read_text(encoding="utf-8")
    if "workflow/state.generated.js" not in index_source:
        errors.append("index.html 未加载生成的工作流状态")
    if re.search(r"这里粘贴 P\d+|\{粘贴同一套", index_source):
        errors.append("index.html 仍包含 Lovart 占位提示词")
    if errors:
        print("工作流校验失败：", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("工作流状态、阶段门禁和生成文件校验通过")
    return 0


def run_capture(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)


def command_preflight(_: argparse.Namespace) -> int:
    state = load_state()
    project = state["project"]
    print(f"project.mode={project['mode']}")
    print(f"database={project['databaseName']}")
    print(f"compose_project={project['composeProjectName']}")
    remote = git_remote()
    print(f"git.origin={remote or '(none)'}")

    docker = run_capture(["docker", "inspect", "mysql-docker", "--format", "{{json .NetworkSettings.Networks}}"])
    if docker.returncode != 0:
        print("mysql-docker: 不可用", file=sys.stderr)
        return 1
    if "shared-network" not in docker.stdout:
        print("mysql-docker: 未接入 shared-network", file=sys.stderr)
        return 1
    print("mysql-docker: 已接入 shared-network")

    db_name = project["databaseName"]
    query = (
        "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA "
        f"WHERE SCHEMA_NAME='{db_name}';"
    )
    database = run_capture(
        [
            "docker", "exec", "mysql-docker", "mysql", "-uroot", "-padmin123",
            "--default-character-set=utf8mb4", "-N", "-e", query,
        ]
    )
    if database.returncode != 0:
        print("数据库存在性检查失败", file=sys.stderr)
        return 1
    exists = database.stdout.strip() == "1"
    print(f"database.exists={'yes' if exists else 'no'}")
    if project["mode"] == "business" and exists:
        print("业务数据库已存在；继续前必须明确记录复用依据，禁止静默覆盖。")
    print("外部工具能力、认证、额度和付费批次仍需在阶段 2/3 由 Agent 记录到门禁证据。")
    return 0


def command_init(args: argparse.Namespace) -> int:
    state = load_state()
    if state["project"].get("mode") != "template":
        raise WorkflowError("当前项目已经不是 template 模式，禁止重复初始化")
    if SCAFFOLD_REMOTE in git_remote():
        raise WorkflowError(
            "origin 仍指向脚手架仓库。请先在业务副本中移除 .git，重新 git init 并绑定业务仓库。"
        )
    if args.database_name == "template_db":
        raise WorkflowError("业务数据库不能使用 template_db")
    if not re.fullmatch(r"[a-zA-Z][a-zA-Z0-9_]{2,63}", args.database_name):
        raise WorkflowError("database-name 格式无效")
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{2,62}", args.compose_project_name):
        raise WorkflowError("compose-project-name 格式无效")

    query = (
        "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA "
        f"WHERE SCHEMA_NAME='{args.database_name}';"
    )
    database = run_capture(
        [
            "docker", "exec", "mysql-docker", "mysql", "-uroot", "-padmin123",
            "--default-character-set=utf8mb4", "-N", "-e", query,
        ]
    )
    if database.returncode != 0:
        raise WorkflowError("无法检查目标数据库是否存在；确认 mysql-docker 和权限后重试")
    if database.stdout.strip() == "1" and not args.reuse_existing_database:
        raise WorkflowError("目标数据库已存在；确认属于本项目后使用 --reuse-existing-database")

    state["project"].update(
        {
            "mode": "business",
            "name": args.project_name,
            "databaseName": args.database_name,
            "composeProjectName": args.compose_project_name,
        }
    )
    workflow = state["workflow"]
    workflow["currentStage"] = 0
    workflow["currentStageStatus"] = "in_progress"
    workflow["completedStages"] = 0
    workflow["stages"][0]["status"] = "in_progress"
    workflow["currentTask"] = "完成业务项目初始化门禁并记录证据。"
    workflow["nextStep"] = "运行 preflight，生成正式文档，删除 templates/ 后关闭阶段 0 门禁。"
    workflow["lastUpdated"] = args.date
    workflow["nextTasks"] = [
        "运行 python3 scripts/workflow.py preflight。",
        "生成正式 PRD、GoalPlan 和设计文档后删除 templates/。",
        "补齐阶段 0 门禁证据，再把阶段 0 标为 completed。",
    ]
    save_state(state)

    APPS_ENV_PATH.write_text(
        "\n".join(
            [
                f"COMPOSE_PROJECT_NAME={args.compose_project_name}",
                f"APP_DB_NAME={args.database_name}",
                f"AUTH_TOKEN_SECRET={secrets.token_urlsafe(48)}",
                "DEEPSEEK_API_KEY=",
                "DEEPSEEK_MODEL=deepseek-v4-pro",
                "",
            ]
        ),
        encoding="utf-8",
    )

    db_source = (ROOT / "db" / "db.sql").read_text(encoding="utf-8")
    (ROOT / "db" / "db.sql").write_text(
        db_source.replace("template_db", args.database_name),
        encoding="utf-8",
    )
    sync_files(state)
    print("业务项目初始化状态已写入；阶段 0 尚未完成，请继续执行门禁。")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("sync", help="从唯一状态源同步生成文件").set_defaults(func=command_sync)
    subparsers.add_parser("validate", help="校验状态、门禁和生成文件").set_defaults(func=command_validate)
    subparsers.add_parser("preflight", help="只读检查 Git、MySQL 容器、网络和数据库").set_defaults(func=command_preflight)

    init_parser = subparsers.add_parser("init", help="在已解除脚手架 Git 关联的业务副本中初始化")
    init_parser.add_argument("--project-name", required=True)
    init_parser.add_argument("--database-name", required=True)
    init_parser.add_argument("--compose-project-name", required=True)
    init_parser.add_argument("--date", default=date.today().isoformat())
    init_parser.add_argument("--reuse-existing-database", action="store_true")
    init_parser.set_defaults(func=command_init)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        return args.func(args)
    except WorkflowError as exc:
        print(f"错误：{exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
